### ISSUE TITLE
Quran() class isnt working properly

### ISSUE THREAD

**Issue by Thuliumitation** [dreygur/Quran.com#1]
Traceback (most recent call last):
  File "F:/taqwa bot/test.py", line 3, in <module>
    print(qur.get_verses(6))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\quran\Quran_api.py", line 134, in get_verses
    return self.rq.get(f"{self.base}chapters/{chapter_id}/verses", kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\quran\MiddleWare.py", line 26, in get
    self.res = requests.get(uri, params=args[0], headers=self.headers)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.quran.com', port=3000): Max retries exceeded with url: /api/v3/chapters/6/verses (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A0205C2400>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Got any advise what I can do with it?

**Comment by dreygur** [comment]
quran.com team has disabled port 3000 and opened 443 and 80.
I have fixed the issue on my side.
Now it's working.

Thanks for the feedback.
